/var/log/fiber-audio-backend/*.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    create 0644 root root
    sharedscripts
    dateext
    dateformat -%Y%m%d-%s
}
